CREATE DATABASE gallery;

USE gallery;

CREATE TABLE `products` (
  `id` INTEGER AUTO_INCREMENT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `is_favorite` BOOLEAN,
  PRIMARY KEY (`id`)
);

CREATE TABLE `images` (
  `id` INTEGER AUTO_INCREMENT NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `product_id` INTEGER NOT NULL,
  PRIMARY KEY (`id`)
)

ALTER TABLE `images`
  ADD CONSTRAINT FOREIGN KEY (`product_id`)
  REFERENCES `products` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;